### ISSUE TITLE
Installation guidelines?

### ISSUE THREAD

**Issue by Jarzka** [layeh/barnard#6]
I think there sould be introductions on how to install this application.

**Comment by UndeRus** [comment]
go get -u github.com/layeh/barnard/cmd/barnard then run binary $GOPATH/bin/barnard

**Comment by jsavage** [comment]
Hi,
I am really please to have found this because I have been looking for a light version of mumble for a headless raspberrypi for sometime.  However, I am new to go so would appreciate further guidance that may also help others who follow.
I have installed go 1.5.2 on Raspberry Pi 2 using the pre-compiled tarball at http://dave.cheney.net/unofficial-arm-tarballs

I have installed sudo apt-get install libopenal1 libopenal-dev  (v1:1.15.1-5)
I have previously tried to install dependencies and compile with 
go get github.com/layeh/barnard
which reported:
../../../layeh/gumble/gumble_openal/gumble_openal.go:104: undefined: openal.DeleteBuffer

I then saw the above guidelines and tried: 
go get -u github.com/layeh/barnard/cmd/barnard  which resulted in the following:

# pkg-config --cflags opus opus
Package opus was not found in the pkg-config search path.
Perhaps you should add the directory containing `opus.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opus' found
Package opus was not found in the pkg-config search path.
Perhaps you should add the directory containing `opus.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opus' found
pkg-config: exit status 1
# github.com/layeh/gumble/gumble_openal
../../../layeh/gumble/gumble_openal/gumble_openal.go:104: undefined: openal.DeleteBuffer

The opus codec libopus0 was already installed but not the -dev package so following a hunch I think I have fixed this with 
sudo apt-get install libopus-dev

So I am now left with the  openal.DeleteBuffer error.   Any hints on how to resolve that?

**Comment by bontibon** [comment]
@jsavage One of the dependencies changed it's API. I have just updated the appropriate code, so try running the following command again:
```shell
go get -u github.com/layeh/barnard/cmd/barnard
```

**Comment by jsavage** [comment]
Wonderful - thank you - it now compiles.

**Comment by branstraub** [comment]
Quick question: How do u set GoPath I'm having quite a struggle with it. When trying to download the project

pi@raspberrypi:~/go/bin $ ./go get -u github.com/layeh/barnard/cmd/barnard
package github.com/layeh/barnard/cmd/barnard: cannot download, $GOPATH not set. For more details see: go help gopath

Regards,

**Comment by Hiradur** [comment]
@branstraub 
Enter this in your terminal before you start the installation:
```shell
export GOPATH=/home/username/go-apps # adapt username!
```

**Comment by Bennig1** [comment]
Hallo I tray to install barnard now sins 2 days but i have problems ;(
my steps 
Clean Raspberry pi Zero 
OS: Rasspian 

1 step after the installation and the network config

i install  Git , mercurial, Go

Git 
$ sudo apt-get install git

Go 
$ sudo apt-get install golang

mercurial

$ sudo apt-get install mercurial

My next step 

$ sudo mkdir -p /home/user/go-apps/src
cd /home/user/go-apps/src
$ sudo export GOPATH=/home/user/go-apps
$ sudo git clone https://github.com/layeh/barnard.git
cd barnard
go get


and now i get the problems see the picture 

https://www.dropbox.com/s/ixhm5nswmf9qa64/IMG_3614.JPG?dl=0


can anyone help me what i do wrong. i am a Raspberry newbie but i like the project idee.
